<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_SeleniumTestNGJUnit Migration to Katalon Studio</name>
   <tag></tag>
   <elementGuidId>a76ee119-48b0-4a99-8363-8c503a54719f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__docusaurus']/div[2]/div/main/div/div/div/div/article/div/ul/li[5]/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c01d48d1-d1c7-406c-83b9-3156b329576d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>xref</value>
      <webElementGuid>f1086ddf-93d0-40b7-9686-7eca66e75694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/docs/get-started/migration-from-other-tools/seleniumtestngjunit-migration-to-katalon-studio</value>
      <webElementGuid>17115b0b-ad16-4778-af8e-85e49fff40a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selenium/TestNG/JUnit Migration to Katalon Studio</value>
      <webElementGuid>1922f119-da57-4dc7-93f9-d7a6722be653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__docusaurus&quot;)/div[@class=&quot;main-wrapper docsWrapper_mKqt&quot;]/div[@class=&quot;docPage_ualW&quot;]/main[@class=&quot;docMainContainer_uL0j&quot;]/div[@class=&quot;container padding-top--md padding-bottom--lg&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col docItemCol_nDMA&quot;]/div[@class=&quot;docItemContainer_p3Qu&quot;]/article[1]/div[@class=&quot;theme-doc-markdown markdown&quot;]/ul[@class=&quot;ul&quot;]/li[@class=&quot;li&quot;]/ul[@class=&quot;ul&quot;]/li[@class=&quot;li&quot;]/a[@class=&quot;xref&quot;]</value>
      <webElementGuid>8683ac81-0e28-4e6c-92e7-63e129b3dcb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__docusaurus']/div[2]/div/main/div/div/div/div/article/div/ul/li[5]/ul/li/a</value>
      <webElementGuid>550befc9-26ba-47df-943b-0782d0e7786b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Studio'])[2]/following::a[1]</value>
      <webElementGuid>94354edb-68ae-49ee-acdb-04932f81f553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Selenium/TestNG/JUnit Migration to']/parent::*</value>
      <webElementGuid>47631553-25e6-44a2-abd3-fa1e9df6012d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/docs/get-started/migration-from-other-tools/seleniumtestngjunit-migration-to-katalon-studio')]</value>
      <webElementGuid>f2b390d6-9c50-4163-9399-e4516ba8ffc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li/a</value>
      <webElementGuid>553f9a1e-771c-4ceb-9329-03e8e4d403eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/docs/get-started/migration-from-other-tools/seleniumtestngjunit-migration-to-katalon-studio' and (text() = 'Selenium/TestNG/JUnit Migration to Katalon Studio' or . = 'Selenium/TestNG/JUnit Migration to Katalon Studio')]</value>
      <webElementGuid>c467d394-d5a0-4fad-a1ae-e64d7b3ff047</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
